# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########
# First, Grant GCP Role IAM service account admin on client management project to config-control SA a.k.a. yakima
# AC-3, AC-3(7), AC-16(2) - This service account possesses minimal privileges(permissions) and is restricted to performing only the necessary operations for resources within the designated namespace. The service account is associated with the current namespace and is assigned minimal permissions to create resources in this namespace only.
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: projects/config-control-sa-iamserviceaccountadmin-client-management-project-id-permissions
  name: config-control-sa-iamserviceaccountadmin-yp-client-mgmt-project-yjs10-permissions # kpt-set: ${management-namespace}-sa-iamserviceaccountadmin-${client-management-project-id}-permissions
  namespace: projects
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMPolicyMember|projects|config-control-sa-iamserviceaccountadmin-client-management-project-id-permissions'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
  # AC-3, AC-3(7), AC-16(2)
  role: roles/iam.serviceAccountAdmin
  member: "serviceAccount:service-298273804134@gcp-sa-yakima.iam.gserviceaccount.com" # kpt-set: serviceAccount:service-${management-project-number}@gcp-sa-yakima.iam.gserviceaccount.com
---
# GCP SA
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata: # kpt-merge: config-control/client-name-config-control-sa
  name: yoppworks-config-control-sa # kpt-set: ${client-name}-${management-namespace}-sa
  namespace: config-control # kpt-set: ${management-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMServiceAccount|config-control|client-name-config-control-sa'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  # TODO: maybe remove client-name prefix to avoid exceeding the 30 chars limit for SA name
  # AC-3, AC-3(7), AC-16(2)
  displayName: yoppworks-config-control-sa # kpt-set: ${client-name}-${management-namespace}-sa
---
# Grant GCP Role Project IAM admin on client management project to GCP client-name-config-control-sa
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: projects/client-name-config-control-sa-projectiamadmin-client-management-project-id-permissions
  name: yoppworks-config-control-sa-projectiamadmin-yp-client-mgmt-project-yjs10-permissions # kpt-set: ${client-name}-${management-namespace}-sa-projectiamadmin-${client-management-project-id}-permissions
  namespace: projects
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMPolicyMember|projects|client-name-config-control-sa-projectiamadmin-client-management-project-id-permissions'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
  # AC-3, AC-3(7), AC-16(2)
  role: roles/resourcemanager.projectIamAdmin
  member: "serviceAccount:yoppworks-config-control-sa@yp-client-mgmt-project-yjs10.iam.gserviceaccount.com" # kpt-set: serviceAccount:${client-name}-${management-namespace}-sa@${client-management-project-id}.iam.gserviceaccount.com
---
# Grant GCP Role IAM service account admin on client management project to GCP client-name-config-control-sa
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: hierarchy/client-name-config-control-sa-iamserviceaccountadmin-client-folder-permissions
  name: yoppworks-config-control-sa-iamserviceaccountadmin-client-folder-permissions # kpt-set: ${client-name}-${management-namespace}-sa-iamserviceaccountadmin-client-folder-permissions
  namespace: hierarchy
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMPolicyMember|hierarchy|client-name-config-control-sa-iamserviceaccountadmin-client-folder-permissions'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Folder
    name: clients.yoppworks # kpt-set: clients.${client-name}
  # AC-3, AC-3(7), AC-16(2)
  role: roles/iam.serviceAccountAdmin
  member: "serviceAccount:yoppworks-config-control-sa@yp-client-mgmt-project-yjs10.iam.gserviceaccount.com" # kpt-set: serviceAccount:${client-name}-${management-namespace}-sa@${client-management-project-id}.iam.gserviceaccount.com
---
# K8S SA
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/client-name-config-control-sa-workload-identity-binding
  name: yoppworks-config-control-sa-workload-identity-binding # kpt-set: ${client-name}-${management-namespace}-sa-workload-identity-binding
  namespace: config-control # kpt-set: ${management-namespace}
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMPartialPolicy|config-control|client-name-config-control-sa-workload-identity-binding'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceRef:
    name: yoppworks-config-control-sa # kpt-set: ${client-name}-${management-namespace}-sa
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
  # AC-3, AC-3(7), AC-16(2)
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:single-kcc-yjs10.svc.id.goog[cnrm-system/cnrm-controller-manager-yoppworks-config-control] # kpt-set: serviceAccount:${management-project-id}.svc.id.goog[cnrm-system/cnrm-controller-manager-${client-name}-${management-namespace}]
---
# K8S namespace
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /client-name-config-control
  name: yoppworks-config-control # kpt-set: ${client-name}-${management-namespace}
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    internal.kpt.dev/upstream-identifier: '|Namespace|default|client-name-config-control'
---
# Link GCP SA to K8S namespace
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata: # kpt-merge: client-name-config-control/configconnectorcontext.core.cnrm.cloud.google.com
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: yoppworks-config-control # kpt-set: ${client-name}-${management-namespace}
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'core.cnrm.cloud.google.com|ConfigConnectorContext|client-name-config-control|configconnectorcontext.core.cnrm.cloud.google.com'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  # AC-3, AC-3(7), AC-16(2)
  googleServiceAccount: yoppworks-config-control-sa@yp-client-mgmt-project-yjs10.iam.gserviceaccount.com # kpt-set: ${client-name}-${management-namespace}-sa@${client-management-project-id}.iam.gserviceaccount.com
