# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########
# GCP SA, has no permissions defined by default, they will be granted on a case by case basis to limit scope
# AC-3, AC-3(7), AC-16(2) - This service account possesses minimal privileges(permissions) and is restricted to performing only the necessary operations for resources within the designated namespace. The service account is associated with the current namespace and is assigned minimal permissions to create resources in this namespace only.
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata: # kpt-merge: client-name-config-control/client-name-admin-sa
  name: yoppworks-admin-sa # kpt-set: ${client-name}-admin-sa
  namespace: yoppworks-config-control # kpt-set: ${client-name}-${management-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMServiceAccount|client-name-config-control|client-name-admin-sa'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  # AC-3, AC-3(7), AC-16(2)
  displayName: yoppworks-admin-sa # kpt-set: ${client-name}-admin-sa
---
# K8S SA
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: client-name-config-control/client-name-admin-sa-workload-identity-binding
  name: yoppworks-admin-sa-workload-identity-binding # kpt-set: ${client-name}-admin-sa-workload-identity-binding
  namespace: yoppworks-config-control # kpt-set: ${client-name}-${management-namespace}
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMPartialPolicy|client-name-config-control|client-name-admin-sa-workload-identity-binding'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceRef:
    name: yoppworks-admin-sa # kpt-set: ${client-name}-admin-sa
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
  # AC-3, AC-3(7), AC-16(2)
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:single-kcc-yjs10.svc.id.goog[cnrm-system/cnrm-controller-manager-yoppworks-admin] # kpt-set: serviceAccount:${management-project-id}.svc.id.goog[cnrm-system/cnrm-controller-manager-${client-name}-admin]
---
# K8S namespace
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /client-name-admin
  name: yoppworks-admin # kpt-set: ${client-name}-admin
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    internal.kpt.dev/upstream-identifier: '|Namespace|default|client-name-admin'
---
# Link GCP SA to K8S namespace
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata: # kpt-merge: client-name-admin/configconnectorcontext.core.cnrm.cloud.google.com
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: yoppworks-admin # kpt-set: ${client-name}-admin
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'core.cnrm.cloud.google.com|ConfigConnectorContext|client-name-admin|configconnectorcontext.core.cnrm.cloud.google.com'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  # AC-3, AC-3(7), AC-16(2)
  googleServiceAccount: yoppworks-admin-sa@yp-client-mgmt-project-yjs10.iam.gserviceaccount.com # kpt-set: ${client-name}-admin-sa@${client-management-project-id}.iam.gserviceaccount.com
---
# Grant viewer role on the client projects namespace to client admin K8S SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: client-name-projects/allow-resource-reference-from-client-name-admin
  name: allow-resource-reference-from-yoppworks-admin # kpt-set: allow-resource-reference-from-${client-name}-admin
  namespace: yoppworks-projects # kpt-set: ${client-name}-projects
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|client-name-projects|allow-resource-reference-from-client-name-admin'
roleRef:
  # AC-3, AC-3(7), AC-16(2)
  name: cnrm-viewer
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cnrm-controller-manager-yoppworks-admin # kpt-set: cnrm-controller-manager-${client-name}-admin
    namespace: cnrm-system
    kind: ServiceAccount
---
# Grant viewer role on the client admin namespace to client projects K8S SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: client-name-admin/allow-resource-reference-from-client-name-projects
  name: allow-resource-reference-from-yoppworks-projects # kpt-set: allow-resource-reference-from-${client-name}-projects
  namespace: yoppworks-admin # kpt-set: ${client-name}-admin
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|client-name-admin|allow-resource-reference-from-client-name-projects'
roleRef:
  # AC-3, AC-3(7), AC-16(2)
  name: cnrm-viewer
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cnrm-controller-manager-yoppworks-projects # kpt-set: cnrm-controller-manager-${client-name}-projects
    namespace: cnrm-system
    kind: ServiceAccount
---
# Grant viewer role on the client networking namespace to client admin K8S SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: client-name-networking/allow-resource-reference-from-client-name-admin
  name: allow-resource-reference-from-yoppworks-admin # kpt-set: allow-resource-reference-from-${client-name}-admin
  namespace: yoppworks-networking # kpt-set: ${client-name}-networking
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|client-name-networking|allow-resource-reference-from-client-name-admin'
roleRef:
  # AC-3, AC-3(7), AC-16(2)
  name: cnrm-viewer
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cnrm-controller-manager-yoppworks-admin # kpt-set: cnrm-controller-manager-${client-name}-admin
    namespace: cnrm-system
    kind: ServiceAccount
---
# Grant viewer role on the client admin namespace to client networking K8S SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: client-name-admin/allow-resource-reference-from-client-name-networking
  name: allow-resource-reference-from-yoppworks-networking # kpt-set: allow-resource-reference-from-${client-name}-networking
  namespace: yoppworks-admin # kpt-set: ${client-name}-admin
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|client-name-admin|allow-resource-reference-from-client-name-networking'
roleRef:
  # AC-3, AC-3(7), AC-16(2)
  name: cnrm-viewer
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cnrm-controller-manager-yoppworks-networking # kpt-set: cnrm-controller-manager-${client-name}-networking
    namespace: cnrm-system
    kind: ServiceAccount
