# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########
# IAM API
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: projects/client-management-project-id-iam
  name: yp-client-mgmt-project-yjs10-iam # kpt-set: ${client-management-project-id}-iam
  namespace: projects
  annotations:
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    internal.kpt.dev/upstream-identifier: 'serviceusage.cnrm.cloud.google.com|Service|projects|client-management-project-id-iam'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceID: iam.googleapis.com
  projectRef:
    external: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
---
# Resource Manager API
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: projects/client-management-project-id-resourcemanager
  name: yp-client-mgmt-project-yjs10-resourcemanager # kpt-set: ${client-management-project-id}-resourcemanager
  namespace: projects
  annotations:
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    internal.kpt.dev/upstream-identifier: 'serviceusage.cnrm.cloud.google.com|Service|projects|client-management-project-id-resourcemanager'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceID: cloudresourcemanager.googleapis.com
  projectRef:
    external: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
---
# Billing API
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: projects/client-management-project-id-billing
  name: yp-client-mgmt-project-yjs10-billing # kpt-set: ${client-management-project-id}-billing
  namespace: projects
  annotations:
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    internal.kpt.dev/upstream-identifier: 'serviceusage.cnrm.cloud.google.com|Service|projects|client-management-project-id-billing'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceID: cloudbilling.googleapis.com
  projectRef:
    external: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
---
# Service Usage API
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: projects/client-management-project-id-serviceusage
  name: yp-client-mgmt-project-yjs10-serviceusage # kpt-set: ${client-management-project-id}-serviceusage
  namespace: projects
  annotations:
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    internal.kpt.dev/upstream-identifier: 'serviceusage.cnrm.cloud.google.com|Service|projects|client-management-project-id-serviceusage'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceID: serviceusage.googleapis.com
  projectRef:
    external: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
---
# Container API
# Required to allow deployment of kubernetes clusters from service account in the client management project
# it could be disabled if the service account would be into the k8s's project
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: projects/client-management-project-id-container
  name: yp-client-mgmt-project-yjs10-container # kpt-set: ${client-management-project-id}-container
  namespace: projects
  annotations:
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    internal.kpt.dev/upstream-identifier: 'serviceusage.cnrm.cloud.google.com|Service|projects|client-management-project-id-container'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceID: container.googleapis.com
  projectRef:
    external: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
---
# Cloud IDS API
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: projects/client-management-project-id-ids
  name: yp-client-mgmt-project-yjs10-ids # kpt-set: ${client-management-project-id}-ids
  namespace: projects
  annotations:
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    internal.kpt.dev/upstream-identifier: 'serviceusage.cnrm.cloud.google.com|Service|projects|client-management-project-id-ids'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceID: ids.googleapis.com
  projectRef:
    external: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
---
# Service Networking API
# required for private service access and cloud IDS
# https://cloud.google.com/vpc/docs/configure-private-services-access
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: projects/client-management-project-id-servicenetworking
  name: yp-client-mgmt-project-yjs10-servicenetworking # kpt-set: ${client-management-project-id}-servicenetworking
  namespace: projects
  annotations:
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/yp-client-mgmt-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    internal.kpt.dev/upstream-identifier: 'serviceusage.cnrm.cloud.google.com|Service|projects|client-management-project-id-servicenetworking'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceID: servicenetworking.googleapis.com
  projectRef:
    external: yp-client-mgmt-project-yjs10 # kpt-set: ${client-management-project-id}
