# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######
# TODO: investigate using client ns, move functionality to client-setup and/or create new client logging project. Will be required if a config-controller is deployed per client OR we need to give permissions to the client service account into the core logging project.
# Cloud Logging bucket for client Platform and Component logs
# Logs are routed using a log sink to a central logging project into a dedicated log bucket
# AU-7, AU-9 - The log buckets created within the Logging project are immutable (AU-7(B)). These buckets have a retention policy of xxx days and IAM Policy that defines who has access to the bucket (AU-9)
# AU-4(1), AU-6(4), AU-9(2), AU-12, AU-12(1) Log sinks sending the logs to same project in same region having a logging bucket
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogBucket
metadata: # kpt-merge: logging/platform-and-component-client-name-log-bucket
  name: platform-and-component-yoppworks-log-bucket # kpt-set: platform-and-component-${client-name}-log-bucket
  namespace: logging
  annotations:
    internal.kpt.dev/upstream-identifier: 'logging.cnrm.cloud.google.com|LoggingLogBucket|logging|platform-and-component-client-name-log-bucket'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  # AU-4(1), AU-6(4), AU-9(2), AU-12, AU-12(1)
  projectRef:
    name: logging-project-yjs10 # kpt-set: ${logging-project-id}
    namespace: projects
  location: northamerica-northeast1
  description: Cloud Logging bucket for yoppworks Platform and Component logs # kpt-set: Cloud Logging bucket for ${client-name} Platform and Component logs
  # RetentionDays sets the policy where existing log content cannot be changed/deleted for the specified number of days (from setters.yaml), locked setting means policy cannot be changed, ensuring immutability
  # AU-7, AU-9
  locked: false # kpt-set: ${retention-locking-policy}
  retentionDays: 1 # kpt-set: ${retention-in-days}
