# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########
# Cloud NAT northamerica-northeast1
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata: # kpt-merge: networking/hub-nane1-external-nat
  name: hub-nane1-external-nat
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: kcclcz-nonprod-hub-yoppworks # kpt-set: ${hub-project-id}
    config.kubernetes.io/depends-on: compute.cnrm.cloud.google.com/namespaces/networking/ComputeRouter/hub-nane1-external-router
    internal.kpt.dev/upstream-identifier: 'compute.cnrm.cloud.google.com|ComputeRouterNAT|networking|hub-nane1-external-nat'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceID: nane1-external-nat
  natIpAllocateOption: AUTO_ONLY
  region: northamerica-northeast1
  routerRef:
    name: hub-nane1-external-router
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
---
# Cloud Router northamerica-northeast1
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata: # kpt-merge: networking/hub-nane1-external-router
  name: hub-nane1-external-router
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: kcclcz-nonprod-hub-yoppworks # kpt-set: ${hub-project-id}
    config.kubernetes.io/depends-on: compute.cnrm.cloud.google.com/namespaces/networking/ComputeNetwork/hub-global-external-vpc
    internal.kpt.dev/upstream-identifier: 'compute.cnrm.cloud.google.com|ComputeRouter|networking|hub-nane1-external-router'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  resourceID: nane1-external-router
  description: northamerica-northeast1 External VPC router
  networkRef:
    name: hub-global-external-vpc
  region: northamerica-northeast1
