# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########
# Project
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata: # kpt-merge: client-name-projects/project-id
  name: client-project-yjs10 # kpt-set: ${project-id}
  namespace: yoppworks-projects # kpt-set: ${client-name}-projects
  annotations:
    cnrm.cloud.google.com/auto-create-network: "false"
    internal.kpt.dev/upstream-identifier: 'resourcemanager.cnrm.cloud.google.com|Project|client-name-projects|project-id'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  name: client-project-yjs10 # kpt-set: ${project-id}
  billingAccountRef:
    external: "01BDB6-B76EC0-AD2596" # kpt-set: ${project-billing-id}
  folderRef:
    name: standard.applications.nonp # kpt-set: ${project-parent-folder}
    namespace: yoppworks-hierarchy # kpt-set: ${client-name}-hierarchy
---
# Activate service project
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCServiceProject
metadata: # kpt-merge: client-name-networking/project-id-svpcservice
  name: client-project-yjs10-svpcservice # kpt-set: ${project-id}-svpcservice
  namespace: yoppworks-networking # kpt-set: ${client-name}-networking
  annotations:
    cnrm.cloud.google.com/project-id: net-host-project-yjs10 # kpt-set: ${host-project-id}
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/yoppworks-projects/Project/client-project-yjs10 # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/${client-name}-projects/Project/${project-id}
    internal.kpt.dev/upstream-identifier: 'compute.cnrm.cloud.google.com|ComputeSharedVPCServiceProject|client-name-networking|project-id-svpcservice'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn'
spec:
  projectRef:
    name: client-project-yjs10 # kpt-set: ${project-id}
    namespace: yoppworks-projects # kpt-set: ${client-name}-projects
